{{- if not .Values.auth.existingSecret }}
{{- $name := printf "%s-auth" (include "spruce.fullname" .) }}
{{- $old := lookup "v1" "Secret" .Release.Namespace $name }}
{{- $peer := .Values.auth.peerToken }}
{{- $client := .Values.auth.clientToken }}
{{- $admin := .Values.auth.adminToken }}
{{- if and (not $peer) $old }}{{ $peer = (index $old.data "peer-token" | b64dec) }}{{- end }}
{{- if and (not $client) $old (index $old.data "client-token") }}{{ $client = (index $old.data "client-token" | b64dec) }}{{- end }}
{{- if and (not $admin) $old (index $old.data "admin-token") }}{{ $admin = (index $old.data "admin-token" | b64dec) }}{{- end }}
{{- if not $peer }}{{ $peer = randAlphaNum 48 }}{{- end }}
{{- if and (not .Values.auth.allowAnonymous) (not $client) }}{{ $client = randAlphaNum 48 }}{{- end }}
{{- if not $admin }}{{ $admin = randAlphaNum 48 }}{{- end }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ $name }}
  labels:
    {{- include "spruce.labels" . | nindent 4 }}
type: Opaque
stringData:
  peer-token: {{ $peer | quote }}
  {{- with .Values.auth.previousPeerToken }}
  previous-peer-token: {{ . | quote }}
  {{- end }}
  cluster-id: {{ default (printf "%s.%s" .Release.Name .Release.Namespace) .Values.auth.clusterID | quote }}
  {{- with $client }}
  client-token: {{ . | quote }}
  {{- end }}
  {{- with .Values.auth.previousClientToken }}
  previous-client-token: {{ . | quote }}
  {{- end }}
  {{- with $admin }}
  admin-token: {{ . | quote }}
  {{- end }}
  {{- with .Values.auth.previousAdminToken }}
  previous-admin-token: {{ . | quote }}
  {{- end }}
{{- end }}
