{{- if not .Values.auth.existingSecret }}
{{- $name := printf "%s-auth" (include "spruce.fullname" .) }}
{{- $old := lookup "v1" "Secret" .Release.Namespace $name }}
{{- $peer := .Values.auth.peerToken }}
{{- if and (not $peer) $old }}{{ $peer = (index $old.data "peer-token" | b64dec) }}{{- end }}
{{- if not $peer }}{{ $peer = randAlphaNum 48 }}{{- end }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ $name }}
  labels:
    {{- include "spruce.labels" . | nindent 4 }}
type: Opaque
stringData:
  peer-token: {{ $peer | quote }}
  cluster-id: {{ default (printf "%s.%s" .Release.Name .Release.Namespace) .Values.auth.clusterID | quote }}
  {{- with .Values.auth.clientToken }}
  client-token: {{ . | quote }}
  {{- end }}
  {{- with .Values.auth.adminToken }}
  admin-token: {{ . | quote }}
  {{- end }}
{{- end }}
