{{- if .Values.serviceMonitor.enabled }}
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: {{ include "spruce.fullname" . }}
  labels:
    {{- include "spruce.labels" . | nindent 4 }}
spec:
  selector:
    matchLabels:
      spruce.io/metrics: broker
  endpoints:
    - port: {{ include "spruce.scheme" . }}
      interval: {{ .Values.serviceMonitor.interval }}
      {{- if .Values.tls.enabled }}
      scheme: https
      {{- end }}
{{- end }}
