apiVersion: v1
kind: Service
metadata:
  name: {{ include "spruce.fullname" . }}-headless
  labels:
    {{- include "spruce.labels" . | nindent 4 }}
    spruce.io/metrics: broker
spec:
  clusterIP: None
  publishNotReadyAddresses: true
  selector:
    {{- include "spruce.selectorLabels" . | nindent 4 }}
    app.kubernetes.io/component: broker
  ports:
    - name: {{ include "spruce.scheme" . }}
      port: {{ .Values.service.port }}
      targetPort: broker
---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "spruce.fullname" . }}
  labels:
    {{- include "spruce.labels" . | nindent 4 }}
spec:
  type: {{ ternary .Values.gateway.service.type "ClusterIP" .Values.gateway.enabled }}
  selector:
    {{- include "spruce.selectorLabels" . | nindent 4 }}
    app.kubernetes.io/component: {{ ternary "gateway" "broker" .Values.gateway.enabled }}
  ports:
    - name: http
      port: {{ ternary .Values.gateway.service.port .Values.service.port .Values.gateway.enabled }}
      targetPort: {{ ternary "http" "broker" .Values.gateway.enabled }}
