apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - service.yaml
  - statefulset.yaml
  - pdb.yaml
  - networkpolicy.yaml
images:
  - name: ghcr.io/sprucebus/spruce
    newName: ghcr.io/lajosnagyuk/spruce
    newTag: v0.1.0
