apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: spruce-same-namespace-ingress
spec:
  podSelector:
    matchLabels:
      app.kubernetes.io/name: spruce
  policyTypes: [Ingress]
  ingress:
    - from:
        - podSelector:
            matchLabels: {}
      ports:
        - protocol: TCP
          port: 8080
